"""Anomaly detection and alert data models."""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class AnomalyResult(BaseModel):
    """Result of local anomaly scoring for a traffic feature vector."""

    batch_id: str
    anomalous: bool
    score: float = Field(ge=0.0, le=1.0)
    threshold: float = Field(ge=0.0, le=1.0)
    detection_source: Literal["model", "heuristic", "disabled", "unavailable"]
    reason_codes: list[str] = Field(default_factory=list)


class AlertRecord(BaseModel):
    """Local alert generated by the endpoint agent."""

    alert_id: str
    agent_id: str
    batch_id: str
    created_at: datetime
    severity: Literal["low", "medium", "high", "critical"]
    confidence: float = Field(ge=0.0, le=1.0)
    anomaly_score: float = Field(ge=0.0, le=1.0)
    reason_codes: list[str]
    message: str


class AlertEnvelope(BaseModel):
    """JSONL envelope for locally written alerts."""

    type: Literal["alert"] = "alert"
    alert: AlertRecord
