"""create_device_and_posture_tables

Revision ID: 0cbf21eeb79e
Revises: 75cad217489c
Create Date: 2026-01-26 17:52:51.089452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbf21eeb79e'
down_revision: Union[str, Sequence[str], None] = '75cad217489c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os_type', sa.String(length=50), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_hostname'), ['hostname'], unique=False)

    op.create_table('posture_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('antivirus_present', sa.Boolean(), nullable=False),
    sa.Column('antivirus_enabled', sa.Boolean(), nullable=False),
    sa.Column('firewall_enabled', sa.Boolean(), nullable=False),
    sa.Column('disk_encrypted', sa.Boolean(), nullable=False),
    sa.Column('os_up_to_date', sa.Boolean(), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posture_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posture_reports_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posture_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posture_reports_timestamp'))

    op.drop_table('posture_reports')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_hostname'))

    op.drop_table('devices')
    # ### end Alembic commands ###
